// <auto-generated />
using System;
using Joja.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Joja.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Joja.Api.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhatsAppMessageTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Joja.Api.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BannerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("Joja.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "العناية بالبشرة"
                        },
                        new
                        {
                            Id = 2,
                            Name = "العناية بالشعر"
                        },
                        new
                        {
                            Id = 3,
                            Name = "الزيوت الطبيعية"
                        });
                });

            modelBuilder.Entity("Joja.Api.Models.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Language = "en",
                            Name = "Skin Care"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Language = "en",
                            Name = "Hair Care"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Language = "en",
                            Name = "Natural Oils"
                        });
                });

            modelBuilder.Entity("Joja.Api.Models.ContentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("Joja.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Joja.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Joja.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedVariantsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Joja.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "زيت جوجوبا نقي 100% للبشرة والشعر",
                            MainImageUrl = "/images/jojoba.jpg",
                            Name = "زيت الجوجوبا العضوي",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "زبدة شيا طبيعية للترطيب العميق",
                            MainImageUrl = "/images/shea.jpg",
                            Name = "زبدة الشيا الطبيعية",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "زيت أرجان أصلي من المغرب للشعر",
                            MainImageUrl = "/images/argan.jpg",
                            Name = "زيت الأرجان المغربي",
                            Price = 450m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "كريم صبار طبيعي لترطيب البشرة",
                            MainImageUrl = "/images/aloe.jpg",
                            Name = "كريم الألوفيرا",
                            Price = 150m
                        });
                });

            modelBuilder.Entity("Joja.Api.Models.ProductTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pure 100% jojoba oil for skin and hair",
                            Language = "en",
                            Name = "Organic Jojoba Oil",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Natural shea butter for deep moisturizing",
                            Language = "en",
                            Name = "Natural Shea Butter",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Authentic argan oil from Morocco for hair",
                            Language = "en",
                            Name = "Moroccan Argan Oil",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Natural aloe cream for skin moisturizing",
                            Language = "en",
                            Name = "Aloe Vera Cream",
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("Joja.Api.Models.UiTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UiTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "HeroTitle",
                            Language = "ar",
                            Value = "جمال طبيعي من أجلك"
                        },
                        new
                        {
                            Id = 2,
                            Key = "HeroSubtitle",
                            Language = "ar",
                            Value = "اكتشفي مجموعتنا العضوية"
                        },
                        new
                        {
                            Id = 3,
                            Key = "ShopNow",
                            Language = "ar",
                            Value = "تسوقي الآن"
                        },
                        new
                        {
                            Id = 4,
                            Key = "JojaMoments",
                            Language = "ar",
                            Value = "لحظات جوجا"
                        },
                        new
                        {
                            Id = 5,
                            Key = "BestSellers",
                            Language = "ar",
                            Value = "الأكثر مبيعاً"
                        },
                        new
                        {
                            Id = 6,
                            Key = "FilterAll",
                            Language = "ar",
                            Value = "الكل"
                        },
                        new
                        {
                            Id = 7,
                            Key = "AddToCart",
                            Language = "ar",
                            Value = "أضف للسلة"
                        },
                        new
                        {
                            Id = 8,
                            Key = "HeroTitle",
                            Language = "en",
                            Value = "Natural Beauty for You"
                        },
                        new
                        {
                            Id = 9,
                            Key = "HeroSubtitle",
                            Language = "en",
                            Value = "Discover our organic collection"
                        },
                        new
                        {
                            Id = 10,
                            Key = "ShopNow",
                            Language = "en",
                            Value = "Shop Now"
                        },
                        new
                        {
                            Id = 11,
                            Key = "JojaMoments",
                            Language = "en",
                            Value = "Joja Moments"
                        },
                        new
                        {
                            Id = 12,
                            Key = "BestSellers",
                            Language = "en",
                            Value = "Best Sellers"
                        },
                        new
                        {
                            Id = 13,
                            Key = "FilterAll",
                            Language = "en",
                            Value = "All"
                        },
                        new
                        {
                            Id = 14,
                            Key = "AddToCart",
                            Language = "en",
                            Value = "Add to Cart"
                        });
                });

            modelBuilder.Entity("Joja.Api.Models.VideoBanner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VideoBanners");
                });

            modelBuilder.Entity("Joja.Api.Models.CategoryTranslation", b =>
                {
                    b.HasOne("Joja.Api.Models.Category", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Joja.Api.Models.Order", b =>
                {
                    b.HasOne("Joja.Api.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Joja.Api.Models.OrderItem", b =>
                {
                    b.HasOne("Joja.Api.Models.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Joja.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Joja.Api.Models.Product", b =>
                {
                    b.HasOne("Joja.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Joja.Api.Models.ProductTranslation", b =>
                {
                    b.HasOne("Joja.Api.Models.Product", "Product")
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Joja.Api.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Joja.Api.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Joja.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Joja.Api.Models.Product", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
